spring.application.name=05_microservicio_alumnos

#configura el puerto 8002
server.port=8002
#configura la conexion a la base de datos de h2
spring.datasource.url=jdbc:h2:mem:alumnosdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
#configura hibernate para crear la tabla personas automaticamente
spring.jpa.hibernate.ddl-auto=update
#configura el dialecto de hibernate para h2
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
#configura el log de hibernate para mostrar las consultas SQL
spring.jpa.show-sql=true
#configura el formato del log de hibernate
spring.jpa.properties.hibernate.format_sql=true
#propiedades para h2 console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
#configura propiedades de nombrado de columnas por hibernate para evitar problemas con mayusculas y minusculas
spring.jpa.properties.hibernate.physical_naming_strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#tambien la implicita
spring.jpa.properties.hibernate.implicit_naming_strategy=org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl