spring.application.name=09_proyecto_typi_remoto
typi.url.base=https://jsonplaceholder.typicode.com
#puerto del servidor 9001
server.port=9001

# Propiedades JWT
jwt.secret=estaesunaclavesecretamuyseguraybastantelargaparacumplirconlosrequisitosdeminimo32caracteres
jwt.expiration=86400000